language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
node_js:
- stable
script:
- npm test
