language: node_js
notifications:
  email:
    on_success: never
    on_failure: change
branches:
  only:
  - master
  - dev
  - /^v\d+\.\d+(\.\d+)?(-\S*)?$/
node_js:
- "node"
script:
- npm test
after_script:
- npm run coveralls
deploy:
  provider: npm
  email: dovydas@quatrodev.com
  api_key: $SIMPLR_NPM_API_KEY
  skip_cleanup: true
  on:
    tags: true
    repo: SimplrJS/ts-extractor
