export enum ApiItemKinds {
    SourceFile = "source-file",
    Enum = "enum",
    EnumMember = "enum-member",
    Function = "function",
    Interface = "interface",
    Method = "method",
    Namespace = "namespace",
    Parameter = "parameter",
    Property = "property",
    Variable = "variable",
    Type = "type",
    Class = "class",
    ClassProperty = "class-property",
    ClassMethod = "class-method",
    Index = "index",
    Call = "call",
    ClassConstructor = "class-constructor",
    Construct = "construct",
    Export = "export",
    ExportSpecifier = "export-specifier",
    ImportSpecifier = "import-specifier",
    TypeParameter = "type-parameter",
    TypeLiteral = "type-literal",
    FunctionType = "function-type"
}
